"""Registry of statute sources by jurisdiction.

Maps jurisdiction IDs to source adapters and configurations.
Configurations can be loaded from YAML files in sources/ directory.
"""

from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from arch.sources.base import SourceConfig, StatuteSource

if TYPE_CHECKING:
    pass


# Source configs loaded from YAML or defined here
_SOURCE_CONFIGS: dict[str, SourceConfig] = {}


def _load_yaml_configs(sources_dir: Path | None = None) -> dict[str, SourceConfig]:
    """Load source configurations from YAML files.

    YAML files are in sources/ directory, named by jurisdiction:
    - sources/us.yaml
    - sources/us-ca.yaml
    - sources/us-ny.yaml
    """
    sources_dir = sources_dir or Path(__file__).parent.parent.parent.parent / "sources"

    configs = {}
    if not sources_dir.exists():
        return configs

    for yaml_file in sources_dir.glob("*.yaml"):
        try:
            with open(yaml_file) as f:
                data = yaml.safe_load(f)

            if not data:
                continue

            jurisdiction = data.get("jurisdiction", yaml_file.stem)
            configs[jurisdiction] = SourceConfig(
                jurisdiction=jurisdiction,
                name=data.get("name", jurisdiction),
                source_type=data.get("source_type", "html"),
                base_url=data.get("base_url", ""),
                api_key=data.get("api_key"),
                section_url_pattern=data.get("section_url_pattern"),
                toc_url_pattern=data.get("toc_url_pattern"),
                content_selector=data.get("content_selector"),
                title_selector=data.get("title_selector"),
                history_selector=data.get("history_selector"),
                codes=data.get("codes", {}),
                rate_limit=data.get("rate_limit", 0.5),
                max_retries=data.get("max_retries", 3),
                custom_parser=data.get("custom_parser"),
            )
        except Exception as e:
            print(f"Error loading {yaml_file}: {e}")

    return configs


def _get_builtin_configs() -> dict[str, SourceConfig]:
    """Get built-in source configurations."""
    from arch.sources.uslm import get_federal_config

    return {
        "us": get_federal_config(),
        # Ohio
        "us-oh": SourceConfig(
            jurisdiction="us-oh",
            name="Ohio",
            source_type="html",
            base_url="https://codes.ohio.gov",
            section_url_pattern="/ohio-revised-code/section-{section}",
            toc_url_pattern="/ohio-revised-code/title-{code}",
            content_selector="main",
            title_selector="title",
            codes={
                "1": "State Government",
                "3": "Counties",
                "5": "Townships",
                "7": "Municipal Corporations",
                "9": "Agriculture-Animals-Fences",
                "11": "Banks-Savings and Loan Associations",
                "13": "Commercial Transactions",
                "15": "Conservation of Natural Resources",
                "17": "Corporations-Partnerships",
                "19": "Courts-Municipal-Mayor's-County",
                "21": "Courts-Probate-Juvenile",
                "23": "Courts-Common Pleas",
                "25": "Courts-Appellate",
                "27": "Courts-General Provisions-Special Remedies",
                "29": "Crimes-Procedure",
                "31": "Domestic Relations-Children",
                "33": "Education-Libraries",
                "35": "Elections",
                "37": "Health-Safety-Morals",
                "39": "Insurance",
                "41": "Labor and Industry",
                "43": "Liquor",
                "45": "Motor Vehicles-Aeronautics-Watercraft",
                "47": "Occupations-Professions",
                "49": "Public Utilities",
                "51": "Public Welfare",
                "53": "Real Property",
                "55": "Roads-Highways-Bridges",
                "57": "Taxation",
                "58": "Trusts",
                "59": "Veterans-Military Affairs",
                "61": "Water Supply-Sanitation-Ditches",
                "63": "Workforce Development",
            },
        ),
        # Pennsylvania
        "us-pa": SourceConfig(
            jurisdiction="us-pa",
            name="Pennsylvania",
            source_type="html",
            base_url="https://www.palegis.us",
            section_url_pattern="/statutes/consolidated/view-statute?txtType=HTM&ttl={code}&sctn={section}",
            toc_url_pattern="/statutes/consolidated/view-statute?txtType=HTM&ttl={code}",
            content_selector="div.statute-content, div#content, body",
            title_selector="h1, h2.title",
            codes={
                "1": "General Provisions",
                "2": "General Assembly",
                "3": "Administration",
                "4": "Amusements",
                "5": "Athletics and Sports",
                "7": "Banks and Banking",
                "8": "Boroughs and Incorporated Towns",
                "9": "Burial Grounds",
                "10": "Charities",
                "11": "Cities",
                "12": "Commerce and Trade",
                "13": "Commercial Code",
                "14": "Community and Economic Development",
                "15": "Corporations and Unincorporated Associations",
                "16": "Counties",
                "17": "Credit Unions",
                "18": "Crimes and Offenses",
                "19": "Decedents Estates and Fiduciaries",
                "20": "Decedents Estates and Fiduciaries",
                "21": "Detectives and Private Police",
                "22": "Detectives and Private Police",
                "23": "Domestic Relations",
                "24": "Education",
                "25": "Elections",
                "27": "Environmental Resources",
                "28": "Executive Departments",
                "30": "Fish",
                "32": "Forests, Waters and State Parks",
                "34": "Game",
                "35": "Health and Safety",
                "37": "Historical and Museums",
                "38": "Holidays and Observances",
                "39": "Housing Authorities",
                "40": "Insurance",
                "42": "Judiciary and Judicial Procedure",
                "43": "Labor",
                "44": "Law and Justice",
                "45": "Legal Notices and Legislative Reference Bureau",
                "46": "Legislature",
                "47": "Liquor",
                "48": "Lodges, Societies and Clubs",
                "50": "Military Affairs",
                "51": "Military Affairs",
                "52": "Mines and Mining",
                "53": "Municipalities Generally",
                "54": "Names",
                "55": "Navigation",
                "57": "Notaries Public",
                "58": "Oil and Gas",
                "61": "Prisons and Parole",
                "62": "Procurement",
                "63": "Professions and Occupations",
                "64": "Public Authorities and Quasi-Public Corporations",
                "65": "Public Officers",
                "66": "Public Utilities",
                "67": "Public Welfare",
                "68": "Real and Personal Property",
                "69": "Recreation and Sports",
                "71": "State Government",
                "72": "Taxation and Fiscal Affairs",
                "73": "Trade and Commerce",
                "74": "Transportation",
                "75": "Vehicles",
                "77": "Weights and Measures",
                "79": "Wills, Estates and Fiduciaries",
            },
        ),
        # North Carolina
        "us-nc": SourceConfig(
            jurisdiction="us-nc",
            name="North Carolina",
            source_type="html",
            base_url="https://www.ncleg.gov",
            section_url_pattern="/EnactedLegislation/Statutes/HTML/BySection/Chapter_{code}/GS_{section}.html",
            toc_url_pattern="/EnactedLegislation/Statutes/HTML/ByChapter/Chapter_{code}.html",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "Civil Procedure",
                "1A": "Rules of Civil Procedure",
                "1B": "Arbitration",
                "1C": "Prelitigation Mediation",
                "2": "Agriculture",
                "2A": "Agriculture Development and Financing",
                "3": "Elections",
                "4": "State of North Carolina",
                "5": "Cemeteries",
                "5A": "Abandoned Cemeteries",
                "6": "Charitable Organizations and Fundraising",
                "7": "Clerks of Superior Courts",
                "7A": "Judicial Department",
                "7B": "Juvenile Code",
                "8": "Estates of Decedents",
                "8B": "Estates of Missing Persons",
                "8C": "Evidence Code",
                "9": "Elections",
                "10": "Corporations",
                "10A": "Nonprofit Corporations",
                "10B": "Savings Institutions",
                "11": "Estates of Decedents",
                "12": "Counties",
                "13": "Conservation and Development",
                "14": "Criminal Law",
                "15": "Criminal Procedure",
                "15A": "Criminal Procedure Act",
                "15B": "Victims Rights",
                "15C": "Sex Offender Registration",
                "16": "Courts",
                "17": "Disabled Persons",
                "18B": "Alcoholic Beverages",
                "18C": "North Carolina Lottery",
                "19": "Counties",
                "20": "Motor Vehicles",
                "21": "Drainage",
                "22": "Commerce",
                "22B": "Electronic Commerce",
                "22C": "Consumer Protection",
                "23": "Drainage Districts",
                "24": "Elections",
                "25": "Uniform Commercial Code",
                "26": "Estates and Trusts",
                "27": "Fences",
                "28A": "Administration of Decedents Estates",
                "28C": "Fiduciary Administration",
                "29": "Property Rights of Married Women",
                "30": "Limitation of Actions",
                "31": "Wills",
                "31A": "Uniform Disclaimer of Property Interests",
                "31B": "Uniform Statutory Will",
                "31C": "Statutory Short Form Power of Attorney",
                "32": "Wills",
                "32A": "Powers of Attorney",
                "32C": "Uniform Power of Attorney Act",
                "33A": "Trusts",
                "33B": "Uniform Trust Code",
                "34": "Notaries",
                "35A": "Incompetency and Guardianship",
                "35B": "Uniform Adult Guardianship Act",
                "36A": "Certain Fiduciaries",
                "36C": "Uniform Trust Code",
                "37": "Trials",
                "38": "Counties",
                "38A": "Special Assessments",
                "39": "Estates",
                "40A": "Eminent Domain",
                "41": "Estates",
                "42": "Landlord and Tenant",
                "43": "Public Records",
                "44": "Liens",
                "44A": "Statutory Liens and Charges",
                "45": "Mortgages and Deeds of Trust",
                "46": "Partition",
                "47": "Real Property Recording",
                "47A": "Residential Property Disclosure",
                "47B": "Condominiums",
                "47C": "Unit Ownership",
                "48": "Adoptions",
                "48A": "Child Placement",
                "49": "Gifts to Minors",
                "50": "Divorce",
                "50A": "Custody",
                "50B": "Domestic Violence",
                "50C": "Civil No-Contact Orders",
                "51": "Marriage",
                "52": "Name Change",
                "52A": "Marriage",
                "52B": "Family Law Arbitration",
                "52C": "Interstate Family Support",
                "53": "Banks",
                "53B": "Banking",
                "53C": "Money Transmitters",
                "54": "Building and Loan Associations",
                "54A": "Savings Banks",
                "54B": "Savings and Loan Associations",
                "54C": "Savings Institutions",
                "55": "Business Corporations",
                "55A": "Professional Corporations",
                "55B": "Limited Liability Companies",
                "56": "Public Service",
                "57": "Secret Societies",
                "57C": "Limited Liability Companies",
                "58": "Insurance",
                "59": "Partnerships",
                "59A": "Registered Limited Liability Partnership",
                "59B": "Revised Uniform Partnership Act",
                "60": "Landlord and Tenant",
                "62": "Public Utilities",
                "63": "Aeronautics",
                "63A": "Aviation",
                "64": "Cemeteries",
                "65": "Handicapped Persons",
                "66": "Commerce and Business",
                "67": "Peddlers, Itinerant Merchants",
                "68": "Partnerships",
                "69": "Libraries",
                "70": "Railroads",
                "71": "Hospitals",
                "72": "Veterans",
                "73": "Strikes and Lockouts",
                "74": "Navigation and Pilotage",
                "75": "Monopolies, Trusts, Consumer Protection",
                "75A": "Boating and Water Safety",
                "75B": "Bedding",
                "75C": "Cable Television",
                "76": "Elections",
                "77": "Rivers, Creeks, and Drainage",
                "78A": "Corporations",
                "78B": "Nonprofit Corporations",
                "78C": "Securities",
                "79": "Public Lands",
                "80": "Warehouses",
                "81A": "State Departments and Agencies",
                "81B": "Open Meetings",
                "82": "State Personnel System",
                "83": "State Retirement System",
                "84": "Attorneys",
                "85": "Surveyors",
                "85A": "Architects and Engineers",
                "85B": "Landscape Architects",
                "86A": "Electrical Contractors",
                "86B": "Auctioneers",
                "86C": "Real Estate Appraisers",
                "87": "Plumbing, Heating Contractors",
                "88": "Veterinarians",
                "88A": "Social Workers",
                "88B": "Fee-Based Pastoral Counselors",
                "89": "Optometry",
                "89A": "Podiatrists",
                "89B": "Hearing Aid Dealers",
                "89C": "Respiratory Care",
                "90": "Medicine and Allied Occupations",
                "90A": "Nursing Home Administrators",
                "90B": "Social Work Certification",
                "90C": "Marriage and Family Therapy",
                "91": "Morticians",
                "91A": "Psychology Practice",
                "92": "Nurses",
                "93": "Pharmacists",
                "93A": "Pharmacy Practice",
                "93B": "Controlled Substances",
                "94": "Contractors",
                "95": "Department of Labor",
                "96": "Employment Security",
                "97": "Workers Compensation",
                "99A": "Industrial Commission Procedure",
                "100": "Juries",
                "101": "Witnesses",
                "102": "Militia",
                "103": "Explosives",
                "104": "Libel and Slander",
                "105": "Taxation",
                "105A": "Tax Administration",
                "106": "Agriculture",
                "106A": "Agriculture Commerce",
                "106B": "Agritourism",
                "107": "Coal",
                "108A": "Social Services",
                "108B": "Public Assistance",
                "109": "Sewage Systems",
                "110": "Child Care Facilities",
                "111": "Migrant Housing",
                "112": "Soil Additives",
                "113": "Conservation and Development",
                "113A": "Pollution Control",
                "114": "Air Conservation",
                "115": "Industrial Development",
                "115A": "Industrial Development Finance",
                "115C": "Elementary and Secondary Education",
                "116": "Higher Education",
                "116A": "Higher Education Bonds",
                "116B": "Education Programs",
                "116C": "School Violence Prevention",
                "117": "Counties",
                "118": "Fences and Stock Law",
                "119": "Internal Improvements",
                "120": "Legislative Branch",
                "121": "State Lands",
                "122": "Energy Policy",
                "122A": "Utilities Commission",
                "122B": "Energy Programs",
                "122C": "Mental Health",
                "123": "Parks",
                "124": "Unemployment Compensation",
                "125": "Fireworks",
                "126": "State Personnel",
                "127": "State Budget",
                "128": "Burial Grounds",
                "129": "Fire Marshal",
                "130": "Wildlife Resources",
                "130A": "Public Health",
                "130B": "Bioterrorism",
                "131": "Public Health",
                "131A": "Building Code",
                "131B": "Unsafe Buildings",
                "131C": "Code Officials Qualification Board",
                "132": "Public Records",
                "133": "Public Contracts",
                "134": "Industrial Development Financing",
                "135": "Veterans",
                "136": "Roads and Highways",
                "137": "Streets",
                "138": "State Lottery",
                "138A": "Ethics and Lobbying",
                "138B": "Elections",
                "139": "Internal Revenue",
                "140": "Fiscal Control",
                "141": "Community Development",
                "142": "Community Trust",
                "143": "State Departments",
                "143A": "Department of Administration",
                "143B": "Department of Health",
                "143C": "State Budget",
                "144": "Sanitation",
                "145": "Streets",
                "146": "Regulation of Public Lands",
                "147": "State Officers and Employees",
                "148": "State Prison System",
                "149": "State Buildings",
                "150": "Administration Act",
                "150A": "Emergency Management",
                "150B": "Administrative Procedure Act",
                "153": "Coroners",
                "153A": "Counties",
                "154": "Towns",
                "155": "Civil Defense",
                "156": "Regional Transit Authority",
                "157": "Curfew",
                "158": "Counties and Cities",
                "159": "Local Government Finance",
                "159A": "State Debt",
                "159B": "Solid Waste Management",
                "159C": "Regional Sewage Disposal",
                "160": "Cities and Towns",
                "160A": "Cities and Towns",
                "160B": "Metropolitan Governments",
                "160C": "Metropolitan Government",
                "161": "Jails",
                "162": "Public Officers",
                "163": "Elections",
                "163A": "Campaign Finance",
                "164": "Legislative Apportionment",
                "166": "Emergency Management",
                "166A": "Emergency Management",
                "168": "Discrimination",
                "168A": "Persons with Disabilities",
                "115D": "Community Colleges",
                "116D": "Coordination",
                "116E": "Education",
                "122D": "Substance Abuse Treatment",
                "122E": "Developmental Disabilities",
                "131D": "Adult Care Homes",
                "131E": "Health Care Facilities",
                "131F": "Solicitation of Contributions",
                "159D": "Local Government Grant Programs",
                "159G": "Water Infrastructure",
                "159I": "Education Funding",
                "160D": "Land Development",
                "1D": "Damages",
                "1E": "Derivative Actions",
                "31D": "Health Care Powers of Attorney",
                "47E": "Residential Rental Agreements",
                "47F": "Planned Community Act",
                "47G": "Property",
                "47H": "Property",
                "50D": "Permanent Civil No-Contact Order",
                "55D": "Filings",
                "57D": "Limited Liability Companies",
                "75D": "Telephone Solicitations",
                "75E": "Internet Service Providers",
                "78D": "Commodity",
                "86D": "Alarm Systems",
                "89D": "Midwifery",
                "89E": "Occupational Therapy",
                "90D": "Professional Counselors",
                "93D": "Wholesale Drug Distributors",
                "93E": "Precursor Chemicals",
            },
        ),
        # Illinois
        "us-il": SourceConfig(
            jurisdiction="us-il",
            name="Illinois",
            source_type="html",
            base_url="https://www.ilga.gov",
            section_url_pattern="/legislation/ilcs/ilcs4.asp?ActID={act}&ChapterID={code}",
            toc_url_pattern="/legislation/ilcs/ilcs2.asp?ChapterID={code}",
            content_selector="div.ilcs-content, td.content, body",
            title_selector="h1, h2",
            codes={
                "5": "General Provisions",
                "10": "State Government",
                "15": "Executive Branch",
                "20": "Elections",
                "25": "Revenues",
                "30": "Finance",
                "35": "Revenue",
                "40": "Civil Liabilities",
                "45": "Immunities and Privileges",
                "50": "Eminent Domain",
                "55": "Counties",
                "60": "Townships",
                "65": "Municipalities",
                "70": "Special Districts",
                "105": "Schools",
                "110": "Higher Education",
                "205": "Public Utilities",
                "210": "Regulation of Banks and Banking",
                "215": "Insurance",
                "220": "Utilities",
                "225": "Professions and Occupations",
                "230": "Sports and Entertainment",
                "235": "Liquor Control",
                "240": "Agriculture",
                "305": "Public Aid",
                "310": "Housing",
                "315": "Labor",
                "320": "Environment",
                "325": "Animals",
                "330": "Alcoholism and Substance Abuse",
                "335": "Veterans",
                "340": "Wildlife",
                "405": "Mental Health",
                "410": "Public Health",
                "415": "Food Safety",
                "420": "Disabled Persons",
                "505": "Civil Procedure",
                "510": "Courts",
                "515": "Business Organizations",
                "520": "Commercial Transactions",
                "525": "Debtor-Creditor",
                "530": "Real Property",
                "535": "Guardianship",
                "605": "Corrections",
                "610": "Law Enforcement",
                "615": "Criminal Justice",
                "620": "Criminal Offenses",
                "625": "Vehicles",
                "705": "Estates",
                "710": "Inheritance",
                "715": "Trusts",
                "720": "Criminal Offenses",
                "725": "Criminal Procedure",
                "730": "Corrections",
                "735": "Civil Procedure",
                "740": "Civil Liabilities",
                "745": "Immunities and Privileges",
                "750": "Family",
                "755": "Estates",
                "760": "Trusts and Fiduciaries",
                "765": "Property",
                "770": "Property",
                "775": "Human Rights",
                "805": "Business Organizations",
                "810": "Commercial Transactions",
                "815": "Business and Consumer Protection",
                "820": "Employment",
            },
        ),
        # Michigan
        "us-mi": SourceConfig(
            jurisdiction="us-mi",
            name="Michigan",
            source_type="html",
            base_url="https://www.legislature.mi.gov",
            section_url_pattern="/Laws/MCL?objectId=mcl-{section}",
            toc_url_pattern="/Laws/MCL?chapter={code}",
            content_selector="div.content, main, body",
            title_selector="title, h1",
            codes={
                "1": "Constitution of Michigan",
                "2": "Revised Judicature Act",
                "3": "State Officers and Employees",
                "4": "Legislature",
                "5": "Government Operations",
                "6": "Commerce",
                "7": "Corporations",
                "8": "Higher Education",
                "9": "Compacts and Interstate Agreements",
                "10": "Civil Procedure",
                "11": "Criminal Procedure",
                "12": "Public Health",
                "13": "Food and Drugs",
                "14": "Environment",
                "15": "Mining",
                "16": "Health",
                "17": "Mental Health",
                "18": "Corrections",
                "19": "Domestic Relations",
                "20": "Elections",
                "21": "Business and Commercial",
                "22": "Employment",
                "23": "Insurance",
                "24": "Transportation",
                "25": "Property",
                "26": "Agriculture",
                "27": "Animals",
                "28": "Fish and Game",
                "29": "Fire Prevention",
                "30": "Water Resources",
                "31": "Public Recreation",
                "32": "Military Affairs",
                "33": "Veterans",
                "34": "Financial Institutions",
                "35": "Education",
                "36": "Professional Licensing",
                "37": "Consumer Protection",
                "38": "Public Utilities",
                "39": "Taxation",
                "40": "Social Welfare",
                "41": "Zoning and Planning",
                "42": "Counties",
                "43": "Cities and Villages",
                "44": "Townships",
                "45": "Special Districts",
                "46": "Economic Development",
            },
        ),
        # Georgia
        "us-ga": SourceConfig(
            jurisdiction="us-ga",
            name="Georgia",
            source_type="html",
            base_url="https://www.legis.ga.gov",
            section_url_pattern="/api/legislation/document/{session}/{doc_id}",
            toc_url_pattern="/legislation/en-US/Search/Legislation",
            content_selector="body",
            title_selector="title",
            codes={
                "48": "Revenue and Taxation",
                "49": "Social Services",
                "34": "Labor and Industrial Relations",
                "33": "Insurance",
            },
        ),
        # Virginia
        "us-va": SourceConfig(
            jurisdiction="us-va",
            name="Virginia",
            source_type="html",
            base_url="https://law.lis.virginia.gov",
            section_url_pattern="/vacode/title{title}/chapter{chapter}/section{section}/",
            toc_url_pattern="/vacode/title{code}/",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "1": "General Provisions",
                "2.1": "Administrative Process Act",
                "2.2": "Administration of Government",
                "3.2": "Agriculture, Animal Care, and Food",
                "4.1": "Alcoholic Beverage Control",
                "5.1": "Aviation",
                "6.2": "Financial Institutions and Services",
                "7.1": "Notaries and Out-of-State Commissioners",
                "8.01": "Civil Remedies and Procedure",
                "8.2": "Uniform Commercial Code - Sales",
                "8.4": "Uniform Commercial Code - Bank Deposits",
                "8.7": "Uniform Commercial Code - Documents of Title",
                "9.1": "Corporations",
                "10.1": "Conservation",
                "11": "Contracts",
                "12.1": "Corporations",
                "13.1": "Corporations",
                "14.1": "Corporations",
                "15.2": "Counties, Cities and Towns",
                "16.1": "Courts Not of Record",
                "17.1": "Courts of Record",
                "18.2": "Crimes and Offenses Generally",
                "19.2": "Criminal Procedure",
                "20": "Domestic Relations",
                "21": "Drainage, Soil Conservation, Sanitation",
                "22.1": "Education",
                "23.1": "Institutions of Higher Education",
                "24.2": "Elections",
                "25.1": "Eminent Domain",
                "26": "Fiduciaries Generally",
                "27": "Fire Protection",
                "28.2": "Fisheries and Habitat of Tidal Waters",
                "29.1": "Game, Inland Fisheries and Boating",
                "30": "General Assembly",
                "31": "Guardian and Ward",
                "32.1": "Health",
                "33.2": "Highways and Other Surface Transportation Systems",
                "34": "Homestead and Other Exemptions",
                "35.1": "Historic Preservation",
                "36": "Housing",
                "37.2": "Mental Health, Intellectual Disability",
                "38.2": "Insurance",
                "40.1": "Labor and Employment",
                "41.1": "Libraries",
                "42.1": "Libraries",
                "43": "Mechanics and Certain Other Liens",
                "44": "Military and Emergency Laws",
                "45.2": "Mines and Mining",
                "46.2": "Motor Vehicles",
                "47.1": "Notaries and Out-of-State Commissioners",
                "48": "Nuisances",
                "49": "Oaths, Affirmations and Bonds",
                "50": "Partnerships",
                "51.1": "Pensions, Benefits, and Retirement",
                "51.5": "Persons with Disabilities",
                "52": "Police (State)",
                "53.1": "Prisons and Other Methods of Correction",
                "54.1": "Professions and Occupations",
                "55.1": "Property and Conveyances",
                "56": "Public Service Companies",
                "57": "Religious and Charitable Matters",
                "58.1": "Taxation",
                "59.1": "Trade and Commerce",
                "60.2": "Unemployment Compensation",
                "62.1": "Waters of the State, Ports and Harbors",
                "63.2": "Welfare (Social Services)",
                "64.2": "Wills, Trusts, and Fiduciaries",
                "65.2": "Workers Compensation",
                "66": "Juvenile Justice",
                "67": "Virginia Energy Plan",
                "8.1A": "Uniform Commercial Code - General Provisions",
                "8.2A": "Uniform Commercial Code - Leases",
                "8.3A": "Uniform Commercial Code - Negotiable Instruments",
                "8.4A": "Uniform Commercial Code - Funds Transfers",
                "8.5A": "Uniform Commercial Code - Letters of Credit",
                "8.8A": "Uniform Commercial Code - Investment Securities",
                "8.9A": "Uniform Commercial Code - Secured Transactions",
            },
        ),
        # Washington
        "us-wa": SourceConfig(
            jurisdiction="us-wa",
            name="Washington",
            source_type="html",
            base_url="https://app.leg.wa.gov",
            section_url_pattern="/RCW/default.aspx?cite={section}",
            toc_url_pattern="/RCW/default.aspx?cite={code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "1": "General Provisions",
                "2": "Courts of Record",
                "3": "Courts of Limited Jurisdiction",
                "4": "Civil Procedure",
                "5": "Evidence",
                "6": "Enforcement of Judgments",
                "7": "Special Proceedings and Actions",
                "8": "Insolvent Estates",
                "9": "Criminal Procedure and Prosecutions",
                "9A": "Washington Criminal Code",
                "10": "Criminal Procedure",
                "11": "Probate and Trust Law",
                "12": "Courts of Limited Jurisdiction",
                "13": "Juvenile Courts",
                "14": "Aeronautics",
                "15": "Agriculture and Marketing",
                "16": "Animals and Livestock",
                "17": "Weeds and Pests",
                "18": "Businesses and Professions",
                "19": "Business Regulations",
                "20": "Cemeteries",
                "21": "Securities",
                "22": "Banks",
                "23": "Corporations - Nonprofit",
                "23B": "Corporations - Washington Business Corporation Act",
                "24": "Corporations and Associations - Nonprofit",
                "25": "Partnerships",
                "26": "Domestic Relations",
                "27": "Libraries, Museums, and Historical Activities",
                "28A": "Common School Provisions",
                "28B": "Higher Education",
                "28C": "Vocational Education",
                "29A": "Elections",
                "30A": "Washington Commercial Bank Act",
                "30B": "Banks and Banking",
                "31": "Miscellaneous Loan Agencies",
                "32": "Washington Savings Bank Act",
                "33": "Washington Savings Association Act",
                "34": "Administrative Law",
                "35": "Cities and Towns",
                "35A": "Optional Municipal Code",
                "36": "Counties",
                "37": "Federal Areas - Indians",
                "38": "Militia and Military Affairs",
                "39": "Public Contracts and Indebtedness",
                "40": "Public Documents Records and Publications",
                "41": "Public Employment Civil Service and Pensions",
                "42": "Public Officers and Agencies",
                "43": "State Government - Executive",
                "44": "State Government - Legislative",
                "46": "Motor Vehicles",
                "47": "Public Highways and Transportation",
                "48": "Insurance",
                "49": "Labor Regulations",
                "50": "Unemployment Compensation",
                "50A": "Family and Medical Leave",
                "50B": "Long-Term Services and Supports",
                "51": "Industrial Insurance",
                "52": "Fire Protection Districts",
                "53": "Port Districts",
                "54": "Public Utility Districts",
                "56": "Sewer Districts",
                "57": "Water-Sewer Districts",
                "58": "Boundaries and Plats",
                "59": "Landlord and Tenant",
                "60": "Liens",
                "61": "Mortgages, Deeds of Trust, and Real Estate Contracts",
                "62A": "Uniform Commercial Code",
                "63": "Personal Property",
                "64": "Real Property and Conveyances",
                "65": "Recording, Registration, and Legal Publication",
                "66": "Alcoholic Beverage Control",
                "67": "Sports and Recreation",
                "68": "Cemeteries, Morgues and Human Remains",
                "69": "Food, Drugs, Cosmetics, and Poisons",
                "70": "Public Health and Safety",
                "70A": "Environmental Health and Safety",
                "71": "Mental Illness",
                "71A": "Developmental Disabilities",
                "72": "State Institutions",
                "73": "Military and Veterans Affairs",
                "74": "Public Assistance",
                "75": "Food Fish and Shellfish",
                "76": "Forests and Forest Products",
                "77": "Fish and Wildlife",
                "78": "Mines, Minerals, and Petroleum",
                "79": "Public Lands",
                "79A": "Public Recreational Lands",
                "80": "Public Utilities",
                "81": "Transportation",
                "82": "Excise Taxes",
                "83": "Estate Taxation",
                "84": "Property Taxes",
                "85": "Diking and Drainage",
                "86": "Flood Control",
                "87": "Irrigation",
                "88": "Navigation and Harbor Improvements",
                "89": "Reclamation, Soil Conservation",
                "90": "Water Rights - Environment",
                "91": "Waterways",
            },
        ),
        # Arizona
        "us-az": SourceConfig(
            jurisdiction="us-az",
            name="Arizona",
            source_type="html",
            base_url="https://www.azleg.gov",
            section_url_pattern="/ars/{title}/{section}.htm",
            toc_url_pattern="/arsDetail?title={code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "1": "Constitution and State Boundaries",
                "2": "Arizona Legislature",
                "3": "Arizona Revised Statutes",
                "4": "Professions and Occupations",
                "5": "Amusements and Sports",
                "6": "Banks and Financial Institutions",
                "7": "Bonds and Notes",
                "8": "Child Safety",
                "9": "Cities and Towns",
                "10": "Corporations and Associations",
                "11": "Counties",
                "12": "Courts and Civil Proceedings",
                "13": "Criminal Code",
                "14": "Trusts, Estates and Protective Proceedings",
                "15": "Education",
                "16": "Elections and Electors",
                "17": "Game and Fish",
                "18": "Information Technology",
                "19": "Initiative, Referendum and Recall",
                "20": "Insurance",
                "21": "Juries",
                "22": "Justice and Municipal Courts",
                "23": "Labor",
                "24": "Livestock and Animals",
                "25": "Marital and Domestic Relations",
                "26": "Military Affairs and Emergency Management",
                "27": "Mining and Metallurgy",
                "28": "Transportation",
                "29": "Partnership",
                "30": "Power",
                "31": "Prisons and Prisoners",
                "32": "Public Buildings and Improvements",
                "33": "Property",
                "34": "Public Records, Printing and Notices",
                "35": "Public Finances",
                "36": "Public Health and Safety",
                "37": "Public Lands",
                "38": "Public Officers and Employees",
                "39": "Public Records, Printing and Notices",
                "40": "Public Utilities and Carriers",
                "41": "State Government",
                "42": "Taxation",
                "43": "Taxation of Income",
                "44": "Trade and Commerce",
                "45": "Waters",
                "46": "Welfare",
                "47": "Wills and Estates",
                "48": "Special Taxing Districts",
                "49": "Environment",
            },
        ),
        # Massachusetts
        "us-ma": SourceConfig(
            jurisdiction="us-ma",
            name="Massachusetts",
            source_type="html",
            base_url="https://malegislature.gov",
            section_url_pattern="/Laws/GeneralLaws/Part{part}/Title{title}/Chapter{chapter}/Section{section}",
            toc_url_pattern="/Laws/GeneralLaws/Part{part}/Title{title}/Chapter{code}",
            content_selector="div.lawContent, main, body",
            title_selector="h1, title",
            codes={
                "I": "Courts and Judicial Officers",
                "II": "Real Property",
                "III": "Domestic Relations",
                "IV": "Civil Procedure",
                "V": "Statutes, Records and Printed Evidence",
                "VI": "Estates and Fiduciaries",
                "VII": "Cities, Towns and Districts",
                "VIII": "Elections",
                "IX": "Taxation",
                "X": "Public Health",
                "XI": "Corrections",
                "XII": "Criminal Law",
                "XIII": "Registration of Vital Records",
                "XIV": "Military Affairs and Public Safety",
                "XV": "Regulation of Trade",
                "XVI": "General Laws",
            },
        ),
        # Maryland
        "us-md": SourceConfig(
            jurisdiction="us-md",
            name="Maryland",
            source_type="html",
            base_url="https://mgaleg.maryland.gov",
            section_url_pattern="/mgawebsite/Laws/StatuteText?article={code}&section={section}",
            toc_url_pattern="/mgawebsite/Laws/StatuteText?article={code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "AG": "Agriculture",
                "AL": "Alcoholic Beverages",
                "BR": "Business Regulation",
                "BO": "Business Occupations and Professions",
                "CA": "Courts and Judicial Proceedings",
                "CJ": "Courts and Judicial Proceedings",
                "CL": "Commercial Law",
                "CP": "Criminal Procedure",
                "CR": "Criminal Law",
                "CO": "Corporations and Associations",
                "ED": "Education",
                "EL": "Election Law",
                "EN": "Environment",
                "ET": "Estates and Trusts",
                "FI": "Financial Institutions",
                "FL": "Family Law",
                "HG": "Health - General",
                "HO": "Health Occupations",
                "HS": "Human Services",
                "HU": "Housing and Community Development",
                "IN": "Insurance",
                "LG": "Local Government",
                "LE": "Labor and Employment",
                "LL": "Land Use",
                "NR": "Natural Resources",
                "PS": "Public Safety",
                "PU": "Public Utilities",
                "RP": "Real Property",
                "SF": "State Finance and Procurement",
                "SG": "State Government",
                "SP": "State Personnel and Pensions",
                "TG": "Tax - General",
                "TP": "Tax - Property",
                "TR": "Transportation",
            },
        ),
        # Minnesota
        "us-mn": SourceConfig(
            jurisdiction="us-mn",
            name="Minnesota",
            source_type="html",
            base_url="https://www.revisor.mn.gov",
            section_url_pattern="/statutes/cite/{section}",
            toc_url_pattern="/statutes/cite/{code}",
            content_selector="div.statute, main, body",
            title_selector="h1, title",
            codes={
                "1": "Court, Sovereign, State",
                "2": "Legislature",
                "3": "Executive Department",
                "4": "Office of the Governor",
                "5": "Boards and Commissions",
                "6": "State Agencies",
                "7": "Metro Government",
                "8": "Towns",
                "9": "Counties",
                "10": "Local Government",
                "11": "Public Officers",
                "12": "Public Lands and Contracts",
                "13": "Government Data Practices",
                "14": "Administrative Procedure",
                "15": "State Employees",
                "16": "Finance",
                "17": "Investments",
                "18": "Agriculture",
                "19": "Grain",
                "20": "Seeds",
                "21": "Food",
                "22": "Agricultural Commodities",
                "24": "Dairy Products",
                "25": "Fertilizers and Pesticides",
                "27": "Livestock",
                "28": "Meat",
                "29": "Eggs",
                "30": "Food Handlers",
                "31": "Weights and Measures",
                "32": "Dairy",
                "33": "Livestock Health",
                "34": "Brands",
                "35": "Animals",
                "36": "Dogs and Cats",
                "37": "Fairs and Tourism",
                "40": "Agriculture Markets",
                "41": "Farm Loans",
                "43": "Forestry",
                "46": "Banks",
                "47": "Savings Banks",
                "48": "Savings Associations",
                "52": "Credit Unions",
                "53": "Financial Services",
                "55": "Trust Companies",
                "56": "Loans",
                "58": "Mortgages",
                "60": "Insurance",
                "62": "Health Insurance",
                "65": "Automobile Insurance",
                "66": "Life Insurance",
                "68": "Workers Compensation",
                "70": "Unemployment Insurance",
                "72": "Retirement",
                "80": "Commerce",
                "82": "Real Estate",
                "84": "Natural Resources",
                "88": "Forestry",
                "89": "Minerals",
                "90": "Mining",
                "92": "Public Lands",
                "97": "Game and Fish",
                "100": "Hunting",
                "103": "Water",
                "105": "Taxation",
                "115": "Pollution Control",
                "116": "Environmental Quality",
                "118": "Libraries",
                "119": "Archives",
                "120": "Education",
                "121": "Higher Education",
                "122": "Schools",
                "123": "School Districts",
                "124": "School Finance",
                "125": "Teachers",
                "127": "Early Childhood",
                "128": "Vocational Education",
                "129": "Community Education",
                "130": "School Facilities",
                "134": "Airports",
                "136": "Universities",
                "137": "State Colleges",
                "144": "Health",
                "145": "Public Health",
                "148": "Medical Practice",
                "150": "Nursing",
                "151": "Pharmacy",
                "152": "Controlled Substances",
                "153": "Dentistry",
                "154": "Podiatry",
                "155": "Optometry",
                "156": "Chiropractic",
                "157": "Hearing Aids",
                "159": "Funeral Directors",
                "160": "Highways",
                "161": "Trunk Highways",
                "162": "County Roads",
                "163": "Town Roads",
                "168": "Motor Vehicles",
                "169": "Traffic Regulations",
                "171": "Driver Licenses",
                "174": "Transportation",
                "176": "Workers Compensation",
                "177": "Wages",
                "178": "Apprenticeship",
                "179": "Labor Relations",
                "181": "Employment",
                "182": "Employment Agencies",
                "183": "Child Labor",
                "196": "Veterans",
                "200": "Elections",
                "201": "Registration",
                "202": "Campaigns",
                "203": "Ballots",
                "204": "Presidential Elections",
                "205": "Primary Elections",
                "206": "Municipal Elections",
                "207": "Campaign Finance",
                "211": "Political Parties",
                "240": "Housing",
                "241": "Corrections",
                "243": "Probation",
                "244": "Prisons",
                "245": "Human Services",
                "252": "Mental Health",
                "253": "Civil Commitment",
                "256": "Public Welfare",
                "257": "Adoption",
                "259": "Child Protection",
                "260": "Juvenile Court",
                "268": "Unemployment Compensation",
                "270": "Taxation",
                "272": "Property Taxes",
                "273": "Valuation",
                "274": "Tax Levies",
                "278": "Appeals",
                "279": "School Taxes",
                "287": "Deed Taxes",
                "289": "Income Taxes",
                "290": "Corporate Taxes",
                "291": "Estate Taxes",
                "295": "Tobacco Tax",
                "296": "Gasoline Tax",
                "297": "Sales Tax",
                "299": "Gross Receipts",
                "300": "Corporations",
                "302": "Nonprofit Corporations",
                "308": "Partnerships",
                "317": "Cooperatives",
                "322": "Real Property",
                "325": "Landlord Tenant",
                "327": "Condominiums",
                "333": "Mechanics Liens",
                "336": "UCC",
                "340": "Civil Actions",
                "345": "Evidence",
                "357": "Civil Process",
                "359": "Habeas Corpus",
                "360": "Debtor Creditor",
                "383": "Small Claims",
                "462": "Zoning",
                "465": "Counties",
                "469": "Economic Development",
                "473": "Metropolitan Government",
                "477": "Cities",
                "480": "Judiciary",
                "484": "District Courts",
                "487": "Court Reporters",
                "490": "Attorneys",
                "500": "Estates",
                "501": "Wills",
                "507": "Conveyances",
                "508": "Torrens",
                "513": "Mortgages",
                "517": "Decedents Estates",
                "518": "Marriage Dissolution",
                "519": "Marriage",
                "524": "Probate",
                "525": "Guardianship",
                "541": "Limitation of Actions",
                "548": "Assignment for Creditors",
                "550": "Fraudulent Conveyances",
                "557": "Forcible Entry",
                "559": "Landlord Tenant",
                "576": "Notaries",
                "580": "Mortgages",
                "588": "Executions",
                "604": "Torts",
                "609": "Criminal Code",
                "617": "Crimes",
                "624": "Firearms",
                "626": "Peace Officers",
                "629": "Arrests",
                "631": "Juries",
                "634": "Trials",
            },
        ),
        # Wisconsin
        "us-wi": SourceConfig(
            jurisdiction="us-wi",
            name="Wisconsin",
            source_type="html",
            base_url="https://docs.legis.wisconsin.gov",
            section_url_pattern="/document/statutes/{section}",
            toc_url_pattern="/statutes/statutes/{code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "71": "Income and Franchise Taxes",
                "49": "Public Assistance",
                "108": "Unemployment Insurance",
                "103": "Employment Regulations",
                "632": "Insurance Contracts",
            },
        ),
        # Missouri
        "us-mo": SourceConfig(
            jurisdiction="us-mo",
            name="Missouri",
            source_type="html",
            base_url="https://revisor.mo.gov",
            section_url_pattern="/main/OneSection.aspx?section={section}",
            toc_url_pattern="/main/OneChapter.aspx?chapter={code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "143": "Income Tax",
                "208": "Social Services",
                "288": "Employment Security",
                "290": "Labor and Industrial Relations",
                "375": "Insurance",
            },
        ),
        # New Jersey
        "us-nj": SourceConfig(
            jurisdiction="us-nj",
            name="New Jersey",
            source_type="html",
            base_url="https://lis.njleg.state.nj.us",
            section_url_pattern="/nxt/gateway.dll/statutes/1?f=templates&fn=default.htm",
            toc_url_pattern="/nxt/gateway.dll/statutes/1?f=templates&fn=default.htm",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "Courts",
                "2": "Administration of Civil and Criminal Justice",
                "2A": "Administration of Civil and Criminal Justice",
                "2B": "Court Organization and Civil Code",
                "2C": "The New Jersey Code of Criminal Justice",
                "3": "Aeronautics",
                "3A": "Alcoholic Beverages",
                "3B": "Administration of Estates",
                "4": "Agriculture and Domestic Animals",
                "5": "Amusements, Public Exhibitions and Meetings",
                "6": "Aviation",
                "7": "Banking",
                "8": "Boroughs",
                "9": "Children-Juvenile and Domestic Relations Courts",
                "10": "Civil Rights",
                "11": "Civil Service",
                "11A": "Civil Service",
                "12": "Commerce and Navigation",
                "12A": "Commerce and Trade",
                "13": "Conservation and Development",
                "14": "Corporations",
                "14A": "New Jersey Business Corporation Act",
                "15": "Corporations and Associations Not for Profit",
                "15A": "Nonprofit Corporations",
                "16": "Counties and County Officers",
                "17": "Corporations and Institutions for Finance",
                "17B": "Insurance",
                "18": "Education",
                "18A": "Education",
                "19": "Elections",
                "20": "Eminent Domain",
                "21": "Explosives and Fireworks",
                "22": "Fences, Fence-Viewers, Pounds and Domestic Animals",
                "22A": "Fees and Costs",
                "23": "Fish and Game, Wild Birds and Animals",
                "24": "Food and Drugs",
                "25": "Frauds and Fraudulent Conveyances",
                "26": "Health and Vital Statistics",
                "27": "Highways",
                "28": "Hotels",
                "29": "Husband and Wife",
                "30": "Institutions and Agencies",
                "31": "Insurance",
                "32": "Intoxicating Liquors",
                "33": "Intoxicating Liquors",
                "34": "Labor and Workers Compensation",
                "35": "Libraries",
                "36": "Liens",
                "37": "Marriage",
                "38": "Mechanics Liens",
                "38A": "Military and Veterans",
                "39": "Motor Vehicles and Traffic Regulation",
                "40": "Municipalities and Counties",
                "40A": "Municipalities and Counties",
                "41": "Oaths and Affidavits",
                "42": "Partnerships and Limited Partnerships",
                "42A": "Uniform Partnership Act",
                "43": "Pensions and Retirement and Group Insurance",
                "44": "Poor",
                "45": "Professions, Occupations and Businesses",
                "46": "Property",
                "47": "Public Records",
                "47A": "Public Records",
                "48": "Public Utilities",
                "49": "Sale of Securities",
                "50": "Savings and Loan Associations",
                "51": "Seals, Brands and Marks",
                "52": "State Government, Departments and Officers",
                "53": "State Police",
                "54": "Taxation",
                "54A": "New Jersey Gross Income Tax Act",
                "55": "Tenement Houses and Public Housing",
                "56": "Trade Names, Trade-Marks and Unfair Trade Practices",
                "57": "Turnpike, Toll Bridges and Toll Roads",
                "58": "Waters and Water Supply",
                "59": "Claims and Suits Against Public Entities",
            },
            custom_parser="arch.parsers.nj_statutes",  # Needs custom parser
        ),
        # Colorado - Official PDFs from leg.colorado.gov
        "us-co": SourceConfig(
            jurisdiction="us-co",
            name="Colorado",
            source_type="bulk",  # PDF downloads, needs PDF parser
            base_url="https://content.leg.colorado.gov",
            section_url_pattern="/sites/default/files/images/olls/crs2024-title-{title}.pdf",
            toc_url_pattern="/agencies/office-legislative-legal-services/2024-crs-titles-download",
            content_selector="body",
            title_selector="title",
            codes={
                "39": "Taxation",
                "26": "Human Services",
                "8": "Labor and Industry",
                "10": "Insurance",
                "22": "Education",
            },
            custom_parser="arch.parsers.co_statutes",  # Needs PDF parser
        ),
        # Indiana
        "us-in": SourceConfig(
            jurisdiction="us-in",
            name="Indiana",
            source_type="html",
            base_url="https://iga.in.gov",
            section_url_pattern="/laws/current/ic/titles/{title}",
            toc_url_pattern="/laws/current/ic/titles/{code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "6": "Taxation",
                "12": "Human Services",
                "22": "Labor and Safety",
                "27": "Insurance",
            },
        ),
        # Kentucky
        "us-ky": SourceConfig(
            jurisdiction="us-ky",
            name="Kentucky",
            source_type="html",
            base_url="https://apps.legislature.ky.gov",
            section_url_pattern="/law/statutes/statute.aspx?id={section}",
            toc_url_pattern="/law/statutes/chapter.aspx?id={code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "141": "Income Tax",
                "205": "Assistance to Needy Persons",
                "341": "Unemployment Compensation",
                "337": "Wages and Hours",
                "304": "Insurance",
            },
        ),
        # Louisiana
        "us-la": SourceConfig(
            jurisdiction="us-la",
            name="Louisiana",
            source_type="html",
            base_url="https://legis.la.gov",
            section_url_pattern="/Legis/Law.aspx?d={section}",
            toc_url_pattern="/Legis/Laws_Toc.aspx?folder={code}",
            content_selector="div.content, main, body",
            title_selector="h1, title",
            codes={
                "47": "Revenue and Taxation",
                "46": "Public Welfare and Assistance",
                "23": "Labor and Workers Compensation",
                "22": "Insurance",
            },
        ),
        # Oregon
        "us-or": SourceConfig(
            jurisdiction="us-or",
            name="Oregon",
            source_type="html",
            base_url="https://www.oregonlegislature.gov",
            section_url_pattern="/bills_laws/ors/ors{chapter}.html",
            toc_url_pattern="/bills_laws/pages/ors.aspx",
            content_selector="body",
            title_selector="title",
            codes={
                "316": "Personal Income Tax",
                "411": "State Public Assistance",
                "657": "Unemployment Insurance",
                "653": "Minimum Wages; Employment Conditions",
                "746": "Insurance",
            },
        ),
        # Tennessee (via LexisNexis free access)
        "us-tn": SourceConfig(
            jurisdiction="us-tn",
            name="Tennessee",
            source_type="html",
            base_url="https://www.lexisnexis.com",
            section_url_pattern="/hottopics/tncode/",
            toc_url_pattern="/hottopics/tncode/",
            content_selector="body",
            title_selector="title",
            codes={
                "67": "Taxes and Licenses",
                "71": "Welfare",
                "50": "Employer and Employee",
                "56": "Insurance",
            },
            custom_parser="arch.parsers.tn_statutes",  # Needs custom for LexisNexis
        ),
        # Connecticut
        "us-ct": SourceConfig(
            jurisdiction="us-ct",
            name="Connecticut",
            source_type="html",
            base_url="https://www.cga.ct.gov",
            section_url_pattern="/current/pub/chap_{chapter}.htm",
            toc_url_pattern="/current/pub/titles.htm",
            content_selector="body",
            title_selector="title",
            codes={
                "12": "Taxation",
                "17a": "Social and Human Services",
                "31": "Labor",
                "38a": "Insurance",
            },
        ),
        # Iowa
        "us-ia": SourceConfig(
            jurisdiction="us-ia",
            name="Iowa",
            source_type="html",
            base_url="https://www.legis.iowa.gov",
            section_url_pattern="/docs/code/{year}/{section}.pdf",
            toc_url_pattern="/law/statutory",
            content_selector="body",
            title_selector="title",
            codes={
                "422": "Individual Income Tax",
                "239B": "Family Investment Program",
                "96": "Employment Security",
                "91A": "Wage Payment Collection",
                "505": "Insurance",
            },
        ),
        # Oklahoma
        "us-ok": SourceConfig(
            jurisdiction="us-ok",
            name="Oklahoma",
            source_type="html",
            base_url="https://www.oscn.net",
            section_url_pattern="/applications/oscn/DeliverDocument.asp?CiteID={cite}",
            toc_url_pattern="/applications/oscn/Index.asp?ftdb=STOKST&level=1",
            content_selector="body",
            title_selector="title",
            codes={
                "68": "Revenue and Taxation",
                "56": "Poor Persons",
                "40": "Labor",
                "36": "Insurance",
            },
        ),
        # South Carolina
        "us-sc": SourceConfig(
            jurisdiction="us-sc",
            name="South Carolina",
            source_type="html",
            base_url="https://www.scstatehouse.gov",
            section_url_pattern="/code/t{title}c{chapter}.php",
            toc_url_pattern="/code/statmast.php",
            content_selector="body",
            title_selector="title",
            codes={
                "12": "Taxation",
                "43": "Social Services",
                "41": "Labor and Employment",
                "38": "Insurance",
            },
        ),
        # Alabama
        "us-al": SourceConfig(
            jurisdiction="us-al",
            name="Alabama",
            source_type="html",
            base_url="https://alisondb.legislature.state.al.us",
            section_url_pattern="/alison/CodeOfAlabama/1975/{title}-{chapter}-{section}.htm",
            toc_url_pattern="/alison/CodeOfAlabama/1975/coatoc.htm",
            content_selector="body",
            title_selector="title",
            codes={
                "40": "Revenue and Taxation",
                "38": "Public Welfare",
                "25": "Industrial Relations and Labor",
                "27": "Insurance",
            },
        ),
        # Utah
        "us-ut": SourceConfig(
            jurisdiction="us-ut",
            name="Utah",
            source_type="html",
            base_url="https://le.utah.gov",
            section_url_pattern="/xcode/Title{title}/Chapter{chapter}/{title}-{chapter}-S{section}.html",
            toc_url_pattern="/xcode/code.html",
            content_selector="body",
            title_selector="title",
            codes={
                "59": "Revenue and Taxation",
                "35A": "Utah Workforce Services Code",
                "34A": "Utah Labor Code",
                "31A": "Insurance Code",
            },
        ),
        # Nevada
        "us-nv": SourceConfig(
            jurisdiction="us-nv",
            name="Nevada",
            source_type="html",
            base_url="https://www.leg.state.nv.us",
            section_url_pattern="/NRS/NRS-{chapter}.html#{section}",
            toc_url_pattern="/NRS/",
            content_selector="body",
            title_selector="title",
            codes={
                "360": "Revenue and Taxation",
                "422": "Public Assistance",
                "612": "Unemployment Compensation",
                "608": "Compensation, Wages and Hours",
                "679A": "Insurance",
            },
        ),
        # Arkansas
        "us-ar": SourceConfig(
            jurisdiction="us-ar",
            name="Arkansas",
            source_type="html",
            base_url="https://www.lexisnexis.com",
            section_url_pattern="/hottopics/arcode/",
            toc_url_pattern="/hottopics/arcode/",
            content_selector="body",
            title_selector="title",
            codes={
                "26": "Taxation",
                "20": "Public Health and Welfare",
                "11": "Labor and Industrial Relations",
                "23": "Insurance",
            },
            custom_parser="arch.parsers.ar_statutes",
        ),
        # Kansas
        "us-ks": SourceConfig(
            jurisdiction="us-ks",
            name="Kansas",
            source_type="html",
            base_url="https://www.ksrevisor.org",
            section_url_pattern="/statutes/chapters/ch{chapter}/",
            toc_url_pattern="/statutes/ksa.html",
            content_selector="body",
            title_selector="title",
            codes={
                "79": "Taxation",
                "39": "Public Assistance and Welfare",
                "44": "Labor and Industries",
                "40": "Insurance",
            },
        ),
        # Mississippi
        "us-ms": SourceConfig(
            jurisdiction="us-ms",
            name="Mississippi",
            source_type="html",
            base_url="https://www.lexisnexis.com",
            section_url_pattern="/hottopics/mscode/",
            toc_url_pattern="/hottopics/mscode/",
            content_selector="body",
            title_selector="title",
            codes={
                "27": "Taxation and Finance",
                "43": "Public Welfare",
                "71": "Labor and Industries",
                "83": "Insurance",
            },
            custom_parser="arch.parsers.ms_statutes",
        ),
        # New Mexico
        "us-nm": SourceConfig(
            jurisdiction="us-nm",
            name="New Mexico",
            source_type="html",
            base_url="https://nmonesource.com",
            section_url_pattern="/nmos/nmsa/en/nav.do",
            toc_url_pattern="/nmos/nmsa/en/nav.do",
            content_selector="body",
            title_selector="title",
            codes={
                "7": "Taxation",
                "27": "Public Assistance",
                "52": "Workers Compensation",
                "50": "Employment Law",
                "59A": "Insurance",
            },
        ),
        # Nebraska
        "us-ne": SourceConfig(
            jurisdiction="us-ne",
            name="Nebraska",
            source_type="html",
            base_url="https://nebraskalegislature.gov",
            section_url_pattern="/laws/statutes.php?statute={section}",
            toc_url_pattern="/laws/browse-chapters.php",
            content_selector="body",
            title_selector="title",
            codes={
                "77": "Revenue and Taxation",
                "68": "Public Assistance",
                "48": "Labor",
                "44": "Insurance",
            },
        ),
        # West Virginia
        "us-wv": SourceConfig(
            jurisdiction="us-wv",
            name="West Virginia",
            source_type="html",
            base_url="https://www.wvlegislature.gov",
            section_url_pattern="/wvcode/code.cfm?chap={chapter}&art={article}",
            toc_url_pattern="/wvcode/",
            content_selector="body",
            title_selector="title",
            codes={
                "11": "Taxation",
                "9": "Human Services",
                "21": "Labor",
                "33": "Insurance",
            },
        ),
        # Idaho
        "us-id": SourceConfig(
            jurisdiction="us-id",
            name="Idaho",
            source_type="html",
            base_url="https://legislature.idaho.gov",
            section_url_pattern="/statutesrules/idstat/Title{title}/T{title}CH{chapter}/SECT{title}-{chapter}{section}/",
            toc_url_pattern="/statutesrules/idstat/",
            content_selector="body",
            title_selector="title",
            codes={
                "63": "Revenue and Taxation",
                "56": "Public Assistance and Welfare",
                "72": "Workers Compensation",
                "45": "Liens and Labor",
                "41": "Insurance",
            },
        ),
        # Hawaii
        "us-hi": SourceConfig(
            jurisdiction="us-hi",
            name="Hawaii",
            source_type="html",
            base_url="https://www.capitol.hawaii.gov",
            section_url_pattern="/hrscurrent/Vol{vol}/Chr{chapter}/HRS_{chapter}-{section}.htm",
            toc_url_pattern="/hrscurrent/",
            content_selector="body",
            title_selector="title",
            codes={
                "235": "Income Tax",
                "346": "Public Welfare",
                "383": "Hawaii Employment Security",
                "388": "Wages and Hours",
                "431": "Insurance",
            },
        ),
        # Maine
        "us-me": SourceConfig(
            jurisdiction="us-me",
            name="Maine",
            source_type="html",
            base_url="https://legislature.maine.gov",
            section_url_pattern="/statutes/{title}/title{title}sec{section}.html",
            toc_url_pattern="/statutes/",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "General Provisions",
                "2": "Legislature",
                "3": "Executive",
                "4": "Judiciary",
                "5": "Administrative Procedures",
                "7": "Agriculture and Animals",
                "8": "Amusements and Sports",
                "9": "Aeronautics",
                "10": "Commerce and Trade",
                "11": "Uniform Commercial Code",
                "12": "Conservation",
                "13": "Corporations",
                "14": "Court Procedure - Civil",
                "15": "Court Procedure - Criminal",
                "16": "Court Procedure - Evidence",
                "17": "Crimes",
                "19": "Domestic Relations",
                "20": "Education and Cultural Services",
                "21": "Elections",
                "22": "Health and Welfare",
                "23": "Highways",
                "24": "Insurance",
                "25": "Internal Security and Public Safety",
                "26": "Labor and Industry",
                "27": "Libraries, History, Culture",
                "28": "Liquor",
                "29": "Motor Vehicles and Traffic",
                "30": "Municipalities and Counties",
                "31": "Partnerships and Associations",
                "32": "Professions and Occupations",
                "33": "Property",
                "35": "Public Services",
                "36": "Taxation",
                "37": "Veterans and Patriotic Matters",
                "38": "Waters and Navigation",
                "39": "Waters and Navigation - Abandoned Property",
                "9B": "Financial Institutions",
                "9A": "Uniform Commercial Code",
                "13C": "Business Corporations",
                "13B": "Nonprofit Corporations",
                "17A": "Maine Criminal Code",
                "18C": "Decedents Estates and Fiduciary Relations",
                "18B": "Trusts",
                "18A": "Decedents Estates",
                "19A": "Domestic Relations",
                "20A": "Education",
                "21A": "Elections",
                "24A": "Maine Insurance Code",
                "28A": "Liquors",
                "29A": "Motor Vehicles",
                "30A": "Municipalities and Counties",
                "34B": "Behavioral and Developmental Services",
                "34A": "Corrections",
                "35A": "Public Utilities",
                "37B": "Defense and Veterans",
                "37A": "Veterans Services",
                "39A": "Workers Compensation",
            },
        ),
        # New Hampshire
        "us-nh": SourceConfig(
            jurisdiction="us-nh",
            name="New Hampshire",
            source_type="html",
            base_url="https://www.gencourt.state.nh.us",
            section_url_pattern="/rsa/html/V/{chapter}/{chapter}-mrg.htm",
            toc_url_pattern="/rsa/html/nhtoc.htm",
            content_selector="body",
            title_selector="title",
            codes={
                "77": "Taxation of Incomes",
                "161": "Division of Human Services",
                "282-A": "Unemployment Compensation",
                "275": "Hours of Labor",
                "401": "Insurance",
            },
        ),
        # Rhode Island
        "us-ri": SourceConfig(
            jurisdiction="us-ri",
            name="Rhode Island",
            source_type="html",
            base_url="https://webserver.rilegislature.gov",
            section_url_pattern="/Statutes/TITLE{title}/{title}-{chapter}/{title}-{chapter}-{section}.htm",
            toc_url_pattern="/Statutes/",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "General Provisions",
                "2": "Legislature",
                "3": "Constitutional Officers",
                "4": "State Administration",
                "5": "State and Municipal Finance",
                "6": "Commercial Law",
                "7": "Corporations and Associations",
                "8": "Courts and Civil Procedure - Courts",
                "9": "Courts and Civil Procedure - Procedure",
                "10": "Courts and Civil Procedure - Actions and Proceedings",
                "11": "Criminal Offenses",
                "12": "Criminal Procedure",
                "13": "Delinquent and Dependent Children",
                "14": "Domestic Relations",
                "15": "Decedents Estates",
                "16": "Education",
                "17": "Elections",
                "18": "Fish and Wildlife",
                "19": "Insurance",
                "20": "Motor and Other Vehicles",
                "21": "Food and Drugs",
                "22": "Health and Safety",
                "23": "Health and Safety",
                "24": "Highways",
                "25": "Industries and Professions",
                "27": "Insurance",
                "28": "Labor and Labor Relations",
                "29": "Liens",
                "30": "Military Affairs and Defense",
                "31": "Motor and Other Vehicles",
                "32": "Property",
                "33": "Domestic Relations",
                "34": "Property",
                "35": "Revenue and Finance",
                "36": "Revenue and Finance",
                "37": "Public Property and Works",
                "38": "State Affairs and Government",
                "39": "Public Utilities and Carriers",
                "40": "Human Services",
                "41": "State Affairs",
                "42": "State Affairs and Government",
                "43": "Towns",
                "44": "Taxation",
                "45": "Towns and Cities",
                "46": "Waters and Navigation",
                "6A": "Uniform Commercial Code",
                "40.1": "Behavioral Healthcare",
            },
        ),
        # Montana
        "us-mt": SourceConfig(
            jurisdiction="us-mt",
            name="Montana",
            source_type="html",
            base_url="https://leg.mt.gov",
            section_url_pattern="/bills/mca/title_{title:04d}/chapter_{chapter:03d}/part_{part:02d}/section_{section}/",
            toc_url_pattern="/bills/mca_toc/",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "General Provisions",
                "2": "Government Structure",
                "3": "Departments",
                "5": "Intergovernmental Relations",
                "7": "Local Government",
                "10": "Military Affairs and Disaster",
                "13": "Elections",
                "15": "Taxation",
                "17": "State Finance",
                "18": "Public Contracts",
                "19": "Public Retirement Systems",
                "20": "Education",
                "22": "Libraries, Arts, and Antiquities",
                "23": "Parks, Recreation, Sports, Gambling",
                "25": "Procedure and Evidence",
                "26": "Criminal Law and Procedure",
                "27": "Civil Liability and Damages",
                "28": "Obligations",
                "30": "Trade and Commerce",
                "31": "Credit Transactions",
                "32": "Financial Institutions",
                "33": "Insurance",
                "35": "Corporations and Associations",
                "37": "Professions and Occupations",
                "39": "Labor",
                "40": "Families",
                "41": "Minors",
                "42": "Children and Youth",
                "44": "Judicial System",
                "45": "Crimes",
                "46": "Criminal Procedure",
                "50": "Health and Safety",
                "52": "Family Services",
                "53": "Social Services",
                "60": "Highways and Transportation",
                "61": "Motor Vehicles",
                "67": "Aeronautics",
                "69": "Public Utilities",
                "70": "Property",
                "71": "Landlord and Tenant",
                "72": "Decedents Estates",
                "75": "Environmental Protection",
                "76": "Land Use Planning",
                "77": "State Lands",
                "80": "Agriculture",
                "81": "Livestock",
                "82": "Minerals, Oil, and Gas",
                "85": "Water Use",
                "87": "Fish and Wildlife",
                "90": "Natural Resources",
            },
        ),
        # Delaware
        "us-de": SourceConfig(
            jurisdiction="us-de",
            name="Delaware",
            source_type="html",
            base_url="https://delcode.delaware.gov",
            section_url_pattern="/title{title}/c{chapter:03d}/sc{subchapter:02d}/index.html",
            toc_url_pattern="/title{title}/index.html",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "General Provisions",
                "2": "Transportation",
                "3": "Agriculture",
                "4": "Alcoholic Liquors and Marijuana",
                "5": "Banking",
                "6": "Commerce and Trade",
                "7": "Conservation",
                "8": "Corporations",
                "9": "Counties",
                "10": "Courts and Judicial Procedure",
                "11": "Crimes and Criminal Procedure",
                "12": "Decedents Estates and Fiduciary Relations",
                "13": "Domestic Relations",
                "14": "Education",
                "15": "Elections",
                "16": "Health and Safety",
                "17": "Highways",
                "18": "Insurance Code",
                "19": "Labor",
                "20": "Military and Civil Defense",
                "21": "Motor Vehicles",
                "22": "Municipalities",
                "23": "Navigation and Waters",
                "24": "Professions and Occupations",
                "25": "Property",
                "26": "Public Utilities",
                "27": "Religion",
                "28": "Sports and Amusements",
                "29": "State Government",
                "30": "State Taxes",
                "31": "Welfare",
            },
        ),
        # South Dakota
        "us-sd": SourceConfig(
            jurisdiction="us-sd",
            name="South Dakota",
            source_type="html",
            base_url="https://sdlegislature.gov",
            section_url_pattern="/Statutes/Codified_Laws/DisplayStatute.aspx?Type=Statute&Statute={section}",
            toc_url_pattern="/Statutes/Codified_Laws/",
            content_selector="body",
            title_selector="title",
            codes={
                "10": "Taxation",
                "28": "Human Services",
                "61": "Unemployment Compensation",
                "60": "Labor and Employment",
                "58": "Insurance",
            },
        ),
        # North Dakota
        "us-nd": SourceConfig(
            jurisdiction="us-nd",
            name="North Dakota",
            source_type="html",
            base_url="https://ndlegis.gov",
            section_url_pattern="/cencode/t{title}c{chapter}.pdf",
            toc_url_pattern="/cencode/",
            content_selector="body",
            title_selector="title",
            codes={
                "57": "Taxation",
                "50": "Public Welfare",
                "52": "Unemployment Compensation",
                "34": "Labor and Employment",
                "26.1": "Insurance",
            },
        ),
        # Alaska
        "us-ak": SourceConfig(
            jurisdiction="us-ak",
            name="Alaska",
            source_type="html",
            base_url="https://www.akleg.gov",
            section_url_pattern="/basis/statutes.asp#43.{section}",
            toc_url_pattern="/basis/statutes.asp",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "General Provisions",
                "2": "Aeronautics",
                "3": "Agriculture, Animals, and Food",
                "4": "Alcoholic Beverages",
                "5": "Amusements and Sports",
                "6": "Banks and Financial Institutions",
                "7": "Boroughs",
                "8": "Business and Professions",
                "9": "Code of Civil Procedure",
                "10": "Corporations and Associations",
                "11": "Criminal Law",
                "12": "Code of Criminal Procedure",
                "13": "Decedents Estates and Guardianships",
                "14": "Education, Libraries, and Museums",
                "15": "Elections",
                "16": "Fish and Game",
                "17": "Food and Drugs",
                "18": "Health, Safety, and Housing",
                "19": "Highways and Ferries",
                "20": "Infants and Incompetents",
                "21": "Insurance",
                "22": "Judiciary",
                "23": "Labor and Workers Compensation",
                "24": "Legislature and Lobbying",
                "25": "Marital and Domestic Relations",
                "26": "Military Affairs and Veterans",
                "27": "Mining",
                "28": "Motor Vehicles",
                "29": "Municipal Government",
                "30": "Navigation and Harbors",
                "31": "Oil and Gas",
                "32": "Partnership",
                "33": "Prisons and Prisoners",
                "34": "Property",
                "35": "Public Buildings and Works",
                "36": "Public Contracts",
                "37": "Public Finance",
                "38": "Public Land",
                "39": "Public Officers and Employees",
                "40": "Public Records",
                "41": "Public Resources",
                "42": "Public Utilities and Energy",
                "43": "Revenue and Taxation",
                "44": "State Government",
                "45": "Trade and Commerce",
                "46": "Water and Environmental Conservation",
                "47": "Welfare and Social Services",
            },
        ),
        # Vermont
        "us-vt": SourceConfig(
            jurisdiction="us-vt",
            name="Vermont",
            source_type="html",
            base_url="https://legislature.vermont.gov",
            section_url_pattern="/statutes/section/{title}/{chapter}/{section}",
            toc_url_pattern="/statutes/",
            content_selector="body",
            title_selector="title",
            codes={
                "1": "General Provisions",
                "2": "Legislature",
                "3": "Executive",
                "4": "Judiciary",
                "5": "Aeronautics and Surface Transportation",
                "6": "Agriculture",
                "7": "Alcoholic Beverages and Cannabis",
                "8": "Banking and Insurance",
                "9": "Commerce and Trade",
                "10": "Conservation and Development",
                "11": "Corporations and Partnerships",
                "12": "Court Procedure",
                "13": "Crimes and Criminal Procedure",
                "14": "Decedents Estates",
                "15": "Domestic Relations",
                "16": "Education",
                "17": "Elections",
                "18": "Health",
                "19": "Highways",
                "20": "Internal Security and Public Safety",
                "21": "Labor",
                "22": "Libraries and Information Technology",
                "23": "Motor Vehicles",
                "24": "Municipal Government",
                "25": "Navigation and Waters",
                "26": "Professions and Occupations",
                "27": "Property",
                "28": "Public Institutions and Corrections",
                "29": "Public Property and Supplies",
                "30": "Public Service",
                "31": "Recreation and Sports",
                "32": "Taxation and Finance",
                "33": "Human Services",
                "9A": "Uniform Commercial Code",
                "11C": "Mutual Benefit Enterprises",
                "11B": "Nonprofit Corporations",
                "11A": "Business Corporations",
                "14A": "Trusts",
                "15C": "Parentage Proceedings",
                "15B": "Interstate Family Support",
                "15A": "Adoption Act",
                "27A": "Common Interest Ownership",
            },
        ),
        # Wyoming
        "us-wy": SourceConfig(
            jurisdiction="us-wy",
            name="Wyoming",
            source_type="html",
            base_url="https://wyoleg.gov",
            section_url_pattern="/statutes/compress/title{title}.pdf",
            toc_url_pattern="/statutes/",
            content_selector="body",
            title_selector="title",
            codes={
                "39": "Taxation and Revenue",
                "42": "Public Assistance and Social Services",
                "27": "Labor and Employment",
                "26": "Insurance",
            },
        ),
    }


def get_all_configs() -> dict[str, SourceConfig]:
    """Get all source configurations (built-in + YAML)."""
    global _SOURCE_CONFIGS

    if not _SOURCE_CONFIGS:
        _SOURCE_CONFIGS = _get_builtin_configs()
        _SOURCE_CONFIGS.update(_load_yaml_configs())

    return _SOURCE_CONFIGS


def get_config_for_jurisdiction(jurisdiction: str) -> SourceConfig | None:
    """Get source configuration for a jurisdiction."""
    configs = get_all_configs()
    return configs.get(jurisdiction.lower())


def get_source_for_jurisdiction(jurisdiction: str) -> StatuteSource | None:
    """Get a source adapter instance for a jurisdiction.

    Args:
        jurisdiction: Jurisdiction ID (e.g., "us", "us-ca")

    Returns:
        StatuteSource instance or None if not configured
    """
    config = get_config_for_jurisdiction(jurisdiction)
    if not config:
        return None

    # Select adapter based on source type
    if config.source_type == "uslm":
        from arch.sources.uslm import USLMSource

        return USLMSource(config)
    elif config.source_type == "api":
        from arch.sources.api import APISource

        if jurisdiction == "us-ny":
            from arch.sources.api import NYLegislationSource

            return NYLegislationSource(config.api_key)
        return APISource(config)
    else:
        from arch.sources.html import HTMLSource

        return HTMLSource(config)


def list_supported_jurisdictions() -> list[dict]:
    """List all supported jurisdictions with their configs."""
    configs = get_all_configs()
    return [
        {
            "jurisdiction": j,
            "name": c.name,
            "source_type": c.source_type,
            "codes": list(c.codes.keys()),
        }
        for j, c in sorted(configs.items())
    ]


def register_source(jurisdiction: str, config: SourceConfig):
    """Register a source configuration."""
    global _SOURCE_CONFIGS
    _SOURCE_CONFIGS[jurisdiction.lower()] = config
